In [ ]:
# 3-1 모두 1 또는 0인 텐서
import tensorflow as tf

x = tf.ones(shape=(2, 1))
print(x)

y = tf.zeros(shape=(2,1))
print(y)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [ ]:
# 3-2 랜덤텐서
x = tf.random.normal(shape=(3,1), mean=0, stddev=1) # 평균이 0이고 표준 편차가 1인 정규 분포에서 뽑은 랜덤한 값으로 만든 텐서
print(x)

y = tf.random.uniform(shape=(3,1), minval=0, maxval=1) # 0~1 사이의 균등 분포에서 뽑은 랜덤한 값으로 만든 텐서
print(y)

tf.Tensor(
[[-1.6646831 ]
 [-0.8616147 ]
 [-0.23913096]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[0.14655495]
 [0.8303176 ]
 [0.8268324 ]], shape=(3, 1), dtype=float32)


In [ ]:
# 3-4 텐서플로 텐서에 값을 할당하지 못함
x = tf.ones(shape=(2,2))
x[0,0]=0

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
# 5,6,7 텐서플로 변수 만들기, 변수에 값 할당하기, 일부에 값 할당하기
v = tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
print(v)
v.assign(tf.ones((3,1)))
print(v)
v[0,0].assign(3.)
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 1.2132235 ],
       [-0.07516722],
       [-1.0429429 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>


In [ ]:
# 8 assign_add()
v.assign_add(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

In [ ]:
#9 기본적인 수학 연산
a = tf.ones((2,2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a,b)
e *= d

print(a,b,c)
print()
print(d,e)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32) tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32) tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32) tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)
